import { FileText, Table, CheckSquare, FileCheck, Cpu, Workflow } from 'lucide-react'

export const DOCUMENT_STATS = [
  { label: 'Total Documents', value: 124, status: 'info' },
  { label: 'Processing', value: 12, status: 'primary' },
  { label: 'Needs Review', value: 8, status: 'warning' },
  { label: 'Processed', value: 104, status: 'success' },
]

export const MOCK_DOCUMENTS = [
  {
    id: 'DOC-001',
    name: 'Invoice_INV-2026-00452.pdf',
    type: 'Commercial Invoice',
    operation: 'Import',
    reference: 'INV-2026-00452',
    status: 'Needs Review',
    uploadedAt: '2 mins ago',
    containerNumber: 'MSCU1234567',
    billOfLading: 'BL-784512',
    confidence: '78%',
    shipper: 'SINO GLOBAL LTD',
    consignee: 'AHMED WEBS LTD',
    weight: '24,300 KG',
  },
  {
    id: 'DOC-002',
    name: 'Packing_List_PK-890.pdf',
    type: 'Packing List',
    operation: 'Import',
    reference: 'PK-890-2026',
    status: 'Verified',
    uploadedAt: '15 mins ago',
    containerNumber: 'MSCU1234567',
    billOfLading: 'BL-784512',
    confidence: '98%',
    shipper: 'SINO GLOBAL LTD',
    consignee: 'AHMED WEBS LTD',
    weight: '24,300 KG',
  },
  {
    id: 'DOC-003',
    name: 'Weighment_Slip_WS-902.png',
    type: 'Weighment Slip',
    operation: 'Import',
    reference: 'WS-902',
    status: 'Failed',
    uploadedAt: '22 mins ago',
    containerNumber: 'HLXU8902341',
    billOfLading: 'BL-904321',
    confidence: '42%',
    shipper: 'SHANGHAI LOGISTICS',
    consignee: 'AHMED WEBS LTD',
    weight: '24,150 KG',
  },
  {
    id: 'DOC-004',
    name: 'Delivery_Order_DO-778.pdf',
    type: 'Delivery Order',
    operation: 'Import',
    reference: 'DO-778-KICT',
    status: 'Processing',
    uploadedAt: '35 mins ago',
    containerNumber: 'MSCU1234567',
    billOfLading: 'BL-784512',
    confidence: '85%',
    shipper: 'PACIFIC CARRIERS',
    consignee: 'AHMED WEBS LTD',
    weight: '24,300 KG',
  },
  {
    id: 'DOC-005',
    name: 'Export_Invoice_EXP-029.pdf',
    type: 'Commercial Invoice',
    operation: 'Export',
    reference: 'EXP-029-PK',
    status: 'Extracted',
    uploadedAt: '1 hour ago',
    containerNumber: 'TCKU9034215',
    billOfLading: 'BL-EXP-029',
    confidence: '92%',
    shipper: 'AHMED WEBS LTD',
    consignee: 'DUBAI TRADING CORP',
    weight: '18,500 KG',
  },
  {
    id: 'DOC-006',
    name: 'Transport_Note_TN-302.jpg',
    type: 'Transport Note',
    operation: 'Export',
    reference: 'TN-302',
    status: 'Verified',
    uploadedAt: '2 hours ago',
    containerNumber: 'TCKU9034215',
    billOfLading: 'BL-EXP-029',
    confidence: '95%',
    shipper: 'AHMED WEBS LTD',
    consignee: 'DUBAI TRADING CORP',
    weight: '18,500 KG',
  },
  {
    id: 'DOC-007',
    name: 'Customs_Declaration_WeBOC-01.pdf',
    type: 'Customs Document',
    operation: 'Import',
    reference: 'GD-KAR-90231',
    status: 'Processing',
    uploadedAt: '4 hours ago',
    containerNumber: 'HLXU8902341',
    billOfLading: 'BL-904321',
    confidence: '88%',
    shipper: 'SINO GLOBAL LTD',
    consignee: 'AHMED WEBS LTD',
    weight: '24,150 KG',
  },
  {
    id: 'DOC-008',
    name: 'Invoice_CN_8892.pdf',
    type: 'Commercial Invoice',
    operation: 'Import',
    reference: 'INV-CN-8892',
    status: 'Verified',
    uploadedAt: '1 day ago',
    containerNumber: 'CMAU9043210',
    billOfLading: 'BL-88902',
    confidence: '99%',
    shipper: 'NINGBO EXPORTS',
    consignee: 'AHMED WEBS LTD',
    weight: '12,800 KG',
  }
]

export const DOCUMENT_TYPES = [
  'Commercial Invoice',
  'Packing List',
  'Bill of Lading',
  'Delivery Order',
  'Customs Document',
  'Transport Note',
  'Weighment Slip',
  'Other'
]
